logging:
  level: INFO
  loggers:
    com.crud: DEBUG

# Database settings.
database:
  checkConnectionWhileIdle: true
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.cj.jdbc.Driver
  properties:
    charSet: UTF-8
  # the username
  user: root
  # the password
  password: root
  # the JDBC URL; the database is called hello_world
  url: jdbc:mysql://localhost:3306/homestead?useSSL=false
  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT 1"