/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDatabasechangeloglock extends Serializable {

    /**
     * Setter for <code>homestead.DATABASECHANGELOGLOCK.ID</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>homestead.DATABASECHANGELOGLOCK.ID</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>homestead.DATABASECHANGELOGLOCK.LOCKED</code>.
     */
    public void setLocked(Boolean value);

    /**
     * Getter for <code>homestead.DATABASECHANGELOGLOCK.LOCKED</code>.
     */
    public Boolean getLocked();

    /**
     * Setter for <code>homestead.DATABASECHANGELOGLOCK.LOCKGRANTED</code>.
     */
    public void setLockgranted(LocalDateTime value);

    /**
     * Getter for <code>homestead.DATABASECHANGELOGLOCK.LOCKGRANTED</code>.
     */
    public LocalDateTime getLockgranted();

    /**
     * Setter for <code>homestead.DATABASECHANGELOGLOCK.LOCKEDBY</code>.
     */
    public void setLockedby(String value);

    /**
     * Getter for <code>homestead.DATABASECHANGELOGLOCK.LOCKEDBY</code>.
     */
    public String getLockedby();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IDatabasechangeloglock
     */
    public void from(IDatabasechangeloglock from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IDatabasechangeloglock
     */
    public <E extends IDatabasechangeloglock> E into(E into);
}
