/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IEmployee extends Serializable {

    /**
     * Setter for <code>homestead.EMPLOYEE.ID</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>homestead.EMPLOYEE.ID</code>.
     */
    public Long getId();

    /**
     * Setter for <code>homestead.EMPLOYEE.NAME</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>homestead.EMPLOYEE.NAME</code>.
     */
    public String getName();

    /**
     * Setter for <code>homestead.EMPLOYEE.EMAIL</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>homestead.EMPLOYEE.EMAIL</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>homestead.EMPLOYEE.SALARY</code>.
     */
    public void setSalary(Double value);

    /**
     * Getter for <code>homestead.EMPLOYEE.SALARY</code>.
     */
    public Double getSalary();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IEmployee
     */
    public void from(IEmployee from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IEmployee
     */
    public <E extends IEmployee> E into(E into);
}
