/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUser extends Serializable {

    /**
     * Setter for <code>homestead.USER.ID</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>homestead.USER.ID</code>.
     */
    public Long getId();

    /**
     * Setter for <code>homestead.USER.NAME</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>homestead.USER.NAME</code>.
     */
    public String getName();

    /**
     * Setter for <code>homestead.USER.EMAIL</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>homestead.USER.EMAIL</code>.
     */
    public String getEmail();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUser
     */
    public void from(IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUser
     */
    public <E extends IUser> E into(E into);
}
