/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq;


import com.crud.v2.jooq.tables.Databasechangelog;
import com.crud.v2.jooq.tables.Databasechangeloglock;
import com.crud.v2.jooq.tables.Employee;
import com.crud.v2.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Homestead extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>homestead</code>
     */
    public static final Homestead HOMESTEAD = new Homestead();

    /**
     * The table <code>homestead.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>homestead.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>homestead.EMPLOYEE</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>homestead.USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Homestead() {
        super("homestead", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Employee.EMPLOYEE,
            User.USER
        );
    }
}
