/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq;


import com.crud.v2.jooq.tables.Databasechangelog;
import com.crud.v2.jooq.tables.Databasechangeloglock;
import com.crud.v2.jooq.tables.Employee;
import com.crud.v2.jooq.tables.User;


/**
 * Convenience access to all tables in homestead.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>homestead.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>homestead.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>homestead.EMPLOYEE</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>homestead.USER</code>.
     */
    public static final User USER = User.USER;
}
