/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq.tables.pojos;


import com.crud.v2.jooq.tables.interfaces.IEmployee;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements IEmployee {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String email;
    private Double salary;

    public Employee() {}

    public Employee(IEmployee value) {
        this.id = value.getId();
        this.name = value.getName();
        this.email = value.getEmail();
        this.salary = value.getSalary();
    }

    public Employee(
        Long   id,
        String name,
        String email,
        Double salary
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.salary = salary;
    }

    /**
     * Getter for <code>homestead.EMPLOYEE.ID</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>homestead.EMPLOYEE.ID</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>homestead.EMPLOYEE.NAME</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>homestead.EMPLOYEE.NAME</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>homestead.EMPLOYEE.EMAIL</code>.
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>homestead.EMPLOYEE.EMAIL</code>.
     */
    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>homestead.EMPLOYEE.SALARY</code>.
     */
    @Override
    public Double getSalary() {
        return this.salary;
    }

    /**
     * Setter for <code>homestead.EMPLOYEE.SALARY</code>.
     */
    @Override
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(salary);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IEmployee from) {
        setId(from.getId());
        setName(from.getName());
        setEmail(from.getEmail());
        setSalary(from.getSalary());
    }

    @Override
    public <E extends IEmployee> E into(E into) {
        into.from(this);
        return into;
    }
}
