/*
 * This file is generated by jOOQ.
 */
package com.crud.v2.jooq.tables.pojos;


import com.crud.v2.jooq.tables.interfaces.IUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements IUser {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String email;

    public User() {}

    public User(IUser value) {
        this.id = value.getId();
        this.name = value.getName();
        this.email = value.getEmail();
    }

    public User(
        Long   id,
        String name,
        String email
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    /**
     * Getter for <code>homestead.USER.ID</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>homestead.USER.ID</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>homestead.USER.NAME</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>homestead.USER.NAME</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>homestead.USER.EMAIL</code>.
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>homestead.USER.EMAIL</code>.
     */
    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setName(from.getName());
        setEmail(from.getEmail());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }
}
